on:
  push:
  pull_request:

env:
  OVER_PAT: ${{github.token}}

jobs:
  call:
    name: "call workflow"
    permissions:
      write-all
    uses: yellowrook1/project-testing-h1-actions/.github/workflows/workflow_call.yml@main      
    secrets:
      OVER_PAT: ${{env.OVER_PAT}}


