on:
  []


jobs:
  I:
    name: "Testing"
    runs-on: ubuntu-latest
    environment: "<h1>XSSENV</h1><img src=x onerror=alert(1)>"
    env:
      TEST_SECRET: ${{secrets.TEST_SECRET}}
    
      TEST_VAR: ${{vars.TEST_VAR}}
    
      ENV_SECRET: ${{secrets.ENV_SECRET}}
      ENV_VAR: ${{vars.ENV_VAR}}
    
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
    - name: Running
      run: echo "Testing";
           echo "test secret:";
           echo "$TEST_SECRET";
           
           echo "env secret:";
           echo "$ENV_SECRET";
           
           echo "test variable:";
           echo "$TEST_VAR";
  II:
    permissions:
      contents: read
      issues: write
    name: "II"
    runs-on: ubuntu-latest
    environment: "secret env"
    env:
      TEST_SECRET: ${{secrets.TEST_SECRET}}
    
      TEST_VAR: ${{vars.TEST_VAR}}
    
      ENV_SECRET: ${{secrets.ENV_SECRET}}
      ENV_VAR: ${{vars.ENV_VAR}}
    
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
    - name: Running
      run: echo "Testing";
           echo "test secret:";
           echo "$TEST_SECRET";
           
           echo "env secret:";
           echo "$ENV_SECRET";
           
           echo "test variable:";
           echo "$TEST_VAR";
           
           echo "env variable:";
           echo "$ENV_VAR";

           echo "github token value:";
           echo "$GITHUB_TOKEN";

