on:
  push:
  pull_request:

jobs:
  call:
    name: "call workflow"
    permissions:
      write-all
    uses: yellowrook1/project-testing-h1-actions/.github/workflows/workflow_call.yml@main           


