on:
  workflow_dispatch:
env:
  TEST_SECRET: ${{secrets.TEST_SECRET}}
  ENV_SECRET: ${{secrets.ENV_SECRET}}

  TEST_VAR: ${{vars.TEST_VAR}}
  ENV_VAR: ${{vars.ENV_VAR}}

  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


jobs:
  I:
    name: "Testing"
    runs-on: ubuntu-latest
    steps:
    - name: Running
      run: echo "Testing";
           echo "test secret:";
           echo "$TEST_SECRET" | base64 | base64;
           
           echo "env secret:";
           echo "$ENV_SECRET" | base64 | base64;
           
           echo "test variable:";
           echo "$TEST_VAR" | base64 | base64;
           
           echo "env variable:";
           echo "$ENV_VAR" | base64 | base64;

           echo "github token value:";
           echo "$GITHUB_TOKEN" | base64 | base64;

