on:	
  workflow_call

jobs:	
  I:	
    name: "Call??"	
    runs-on: ubuntu-latest	
    env:	
      TEST_SECRET: ${{secrets.TEST_SECRET}}	

      TEST_VAR: ${{vars.TEST_VAR}}	

      ENV_SECRET: ${{secrets.ENV_SECRET}}	
      ENV_VAR: ${{vars.ENV_VAR}}	

      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}	
    steps:	
    - name: Issue_write	
      uses: yellowrook1/project-testing-h1-actions/.github/workflows/issue_write.yml@main
    - name: Contents write
      uses: yellowrook1/project-testing-h1-actions/.github/workflows/contents_write.yml@main
